### ISSUE TITLE
the life bar along with armor turn dark

### ISSUE THREAD

**Issue by CarionDioDa** [HerrBrandstetter/Farsight#1]
the last 2 updates make the health and armor bars go dark
![2021-06-25_19 44 18](https://user-images.githubusercontent.com/86500506/123494752-f25c4c80-d5ee-11eb-8fcd-caa1a4496871.png)
![2021-06-25_19 44 22](https://user-images.githubusercontent.com/86500506/123494754-f4bea680-d5ee-11eb-9cef-04462b8e3dde.png)

**Comment by CarionDioDa** [comment]
I went to test without mods and it got worse kkkkkkkkkkk
![2021-06-25_20 02 39](https://user-images.githubusercontent.com/86500506/123495297-34868d80-d5f1-11eb-828f-8fadd75a20bc.png)

**Comment by HerrBrandstetter** [comment]
Huh 🤔 so because of your last image I‘m wondering, is that really related to your mod or on your end?

**Comment by CarionDioDa** [comment]
the first photo is with a modpack I made, the second is just the "
Farsight"

**Comment by HerrBrandstetter** [comment]
I'm... working on it I guess xD

**Comment by HerrBrandstetter** [comment]
Fixed 👍
