### ISSUE TITLE
Multiplayer issue with Spyglass

### ISSUE THREAD

**Issue by TheSwitzVirgin** [herrbrandstetter/Farsight#7]
Basically only my girlfriend has the Spyglass, but if she looks thgough it, not only zooms on her screen but on mine too, even if I haven't the Spyglass on my inventory or not using it.

**Comment by herrbrandstetter** [comment]
Oof, ok I will look into it!

**Comment by ndg-creative** [comment]
This is happening to us, too!  Is there a fix for this?
